### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by dcousens** [crypto-browserify/browserify-aes#19]
It seems very odd to do:

``` javascript
var aes = require("browserify-aes")
```

I actually just want to use this as an individual component and sub-out for the standard library, and have it **fall-back** on to the standard library if necessary.

Much a-like to `inherits` and `readable-stream` (see http://r.va.gg/2014/06/why-i-dont-use-nodes-core-stream-module.html).

@calvinmetcalf ideas for a better name?

**Comment by calvinmetcalf** [comment]
I think @jprichardson owns [aes](https://www.npmjs.com/package/aes) which seems not to be actively developed anymore

**Comment by jprichardson** [comment]
I don't think that I'd have a problem bring over `aes` and merging repos. Let me think about it.

**Comment by dcousens** [comment]
bump @jprichardson

**Comment by jprichardson** [comment]
I'd be ok with merging the repos and renaming this one. Would it be possible to use the AES algorithm in the package `aes` and bring that code into this repo, so that we can expose it maintain backwards compatibility for those using `aes`?

**Comment by dcousens** [comment]
@jprichardson we could definitely consolidate the code during the merge.

I don't think it would be a straight up replacement,  however,  we could just bump the major w/ an added deprecation warning and therefore we hurt no one?

Were you're thoughts something like `aes/raw` or some such?

**Comment by dcousens** [comment]
Bump @jprichardson

**Comment by jprichardson** [comment]
> Were you're thoughts something like aes/raw or some such?

Yes, this would work for me.

**Comment by calvinmetcalf** [comment]
the actual aes code in browserify aes is fairly gnarly so replacing it wouldn't be the worst thing

**Comment by dcousens** [comment]
Sweet,  happy to take this on @calvinmetcalf @jprichardson

**Comment by dcousens** [comment]
Still planning to do this :dancer:

**Comment by fanatid** [comment]
Any progress?  `browserify-aes` is really bad name :scream: 
+1 for merge with `aes`

**Comment by dcousens** [comment]
@fanatid just a matter of priorities at the moment :)

**Comment by gggin** [comment]
I can also use webpack to build this 
Just use
```javascript
var crypto = require('browserify-aes')
```
replace 
```javascript
var crypto = require('crypto')
```

Why not write this to Readme.txt?

**Comment by dcousens** [comment]
ping @fanatid if you want to do this :P

**Comment by fanatid** [comment]
@dcousens I'd like to do this, but I'm not owner of `browserify-aes`/`aes` on npm :)

**Comment by dcousens** [comment]
pinnnnnnnnnnnnnnng @jprichardson

**Comment by dcousens** [comment]
@jprichardson want to add @fanatid on `npm`? :P
