### ISSUE TITLE
Extract EVP_BytesToKey

### ISSUE THREAD

**Issue by dcousens** [crypto-browserify/browserify-aes#21]
Can we combine the code similarities between the implementation in this repo and https://github.com/crypto-browserify/parse-asn1 ?

@calvinmetcalf ?

It seems the only difference is accounting for an IV.

**Comment by calvinmetcalf** [comment]
I believe that is the only difference

**Comment by dcousens** [comment]
Thoughts, @calvinmetcalf what could we name this module?

**Comment by calvinmetcalf** [comment]
evp_bytestokey?

**Comment by dcousens** [comment]
This was done, see https://github.com/crypto-browserify/EVP_BytesToKey
