### ISSUE TITLE
npmignore

### ISSUE THREAD

**Issue by TrySound** [crypto-browserify/browserify-aes#24]
Add please massive tests to npmignore for smaller package.

**Comment by TrySound** [comment]
Thanks!

**Comment by TrySound** [comment]
Make patch release, please.

**Comment by calvinmetcalf** [comment]
done

**Comment by dcousens** [comment]
ping @dominictarr,  we've had this discussion several times,  I don't think it was agreed upon to do this.
I'm on the fence either way.

**Comment by dominictarr** [comment]
Here is my stance on this issue
https://github.com/dominictarr/JSONStream/issues/75#issuecomment-128772578
and
https://github.com/crypto-browserify/sha.js/issues/5#issuecomment-69824264

You could make a extented campaign to get everyone to make their modules smaller,
but for the reasons in my first link, i don't think it will make much difference.
What would make a difference is to campaign to get @npmjs to design npm to install faster with fewer round trips. This would make by far the biggest difference.

**Comment by calvinmetcalf** [comment]
So usually I do agree with you but this package (and browserify-sign) have
fairly large test fixtures and have confusingly written tests making them
of dubious value for educational purposes.

**Comment by dominictarr** [comment]
I'm not gonna veto this, i've stated my position.
if you guys want to ignore the tests, do it.

**Comment by dcousens** [comment]
@dominictarr what would also be great is for the package manager to allow us to choose (say,  download packages with `developer` intentions?).

**Comment by dominictarr** [comment]
maybe in the perfect world the tests and the product code would be in separate bundles.
