### ISSUE TITLE
Long utf8 plaintexts get corrupted when decrypting.

### ISSUE THREAD

**Issue by dabura667** [crypto-browserify/browserify-aes#26]
Here's the functions I wrote.
```javascript
var Crypto = require('crypto-browserify');

var encrypt = function (txt, passwd, salt) {
  salt = salt || "テストです。この塩を変えた方が安全です。";
  var cipher = Crypto.createCipher('aes-256-cbc',Crypto.pbkdf2Sync(passwd, salt, 8192, 32, 'sha256'));
  var result = cipher.update(txt, 'utf8', 'base64')
  result += cipher.final('base64')
  cipher = null;
  txt = null;
  passwd = null;
  salt = null;
  return result;
};
var decrypt = function (enc, passwd, salt) {
  salt = salt || "テストです。この塩を変えた方が安全です。";
  var decipher = Crypto.createDecipher('aes-256-cbc',Crypto.pbkdf2Sync(passwd, salt, 8192, 32, 'sha256'));
  try {
    var result = decipher.update(enc, 'base64', 'utf8')
    result += decipher.final('utf8')
  } catch(e) {
    return null;
  };
  decipher = null;
  enc = null;
  passwd = null;
  salt = null;
  return result;
};

var enc = encrypt("ふっかつ　あきる　すぶり　はやい　つける　まゆげ　たんさん　みんぞく　ねほりはほり　せまい　たいまつばな　ひはん","a","a");
// gives me "95XLoYZrLtCzx/WDzQ+G5vA293ynWpBhNRyIUV2CTZACSR4HKwWCAIIUklewk/bmTeFvzk7X0yRAQVXnkgwgMfAVs5uDkw6naSWN5akWwLYbEZurjFaQcdncy9wvmmS2c8gOFo90yWNSrQRKlhifmi5ibgVF3HgvDTcksofTjUzzFxaRqINZuHjcVZMiggAAX1etUgZdSM8O33ciWwyv2YBo2EsJOb9z1KyMNXaICK2PtC505Sru9W9q1mnPQOAA"

var dec = decrypt(enc, "a", "a");
// gives me "��" (which is two utf8 characters of "\uFFFD")
```

If you could:
a. tell me if my functions are written wrong, if that's the case.
b. fix the problem if it is a problem with the library.

I would greatly appreciate it. Thanks.

btw, if I just encrypt a short string like ふっかつ and decrypt it it comes out fine.

Also: The text I am trying above is 60 utf8 3 byte characters, but I tried 180 "a"s together and it decrypted fine. I think it's a problem with the base64 >> utf8 conversion or something.

**Comment by calvinmetcalf** [comment]
A couple quick questions?

Does this also happen in node (doubtful but worth a check).

Does this happen if the mode is aes-256-ctr?

Does this happen if you use hex encoding instead of base64?

**Comment by dabura667** [comment]
> Does this also happen in node (doubtful but worth a check).
It worked! (with cbc)

> Does this happen if the mode is aes-256-ctr?
No it doesn't. (it works even in the browser, and in node)

> Does this happen if you use hex encoding instead of base64?
Same exact problem. Two \uFFFD characters come back.

For now, I will just switch to ctr.

**Comment by calvinmetcalf** [comment]
@dabura667 it's generally preferable to use ctr or gcm mode over cbc mode so glad I we were able to solve your short term problem, but I will dig more into this.

**Comment by dabura667** [comment]
@calvinmetcalf Yeah, looking up online that seems to be the case unless you're using a randomized iv. (which I don't plan to for my purposes)

Seems to only be failing in browser, not in node, and only cbc and only when using non-ascii characters in utf-8 mode (so multi-byte utf8)

Thanks for looking into it.

**Comment by calvinmetcalf** [comment]
I believe it is a multi byte utf8 thing as well as changing it to `return Buffer.concat([decipher.update(enc, 'base64'), decipher.final()]).toString('utf8')` instead of `return decipher.update(enc, 'base64', 'utf8'), decipher.final('utf8')` prevents the error meaning it is almost deffinitly an issue with multi byte utf8

**Comment by calvinmetcalf** [comment]
see #27
