### ISSUE TITLE
Method 'setAutoPadding' for StreamCipher, AuthCipher classes.

### ISSUE THREAD

**Issue by zhulduz** [crypto-browserify/browserify-aes#31]
Hi everyone,

As I understood from https://nodejs.org/api/crypto.html a class Cipher always should have the method setAutoPadding, but these classes StreamCipher and AuthCipher in your implementation don't have it.

ssh2 library  https://github.com/mscdex/ssh2 uses this code 

``` coffee
outstate.encrypt.instance = crypto.createCipheriv cipherAlgo, key, iv
outstate.encrypt.instance.setAutoPadding no
```

so it always expects method `setAutoPadding`.

Maybe I something misunderstand, so I will be grateful for any explanation.

Thanks in advance.

**Comment by calvinmetcalf** [comment]
they don't actually do anything for those ciphers which is why they wen't included we can add a noop method through
