### ISSUE TITLE
passwd parameter is not used

### ISSUE THREAD

**Issue by jcalfee** [crypto-browserify/browserify-aes#39]
https://github.com/crypto-browserify/browserify-aes/blob/master/test/index.js#L538-L544

**Comment by calvinmetcalf** [comment]
pull requests accepted, this is a good one for somebody who hasn't done one before

**Comment by geekodour** [comment]
Should this be something like this?
```
  function encrypt (txt) {
    // txt is the plaintext pass
    var cipher = crypto.createCipher('aes-256-cbc', salt)
    return cipher.update(txt, 'utf8', 'base64') + cipher.final('base64')
  }
  function decrypt (enc) {
    // enc is the encrypted pass
    var decipher = crypto.createDecipher('aes-256-cbc', salt)
    return decipher.update(enc, 'base64', 'utf8') + decipher.final('utf8')
}
```
because we don't need the passwd argument. is this going in the right direction?

**Comment by calvinmetcalf** [comment]
yeah it should look pretty much the same just without the password argument

**Comment by geekodour** [comment]
should I send a PR with the same?
