### ISSUE TITLE
Test suite fail under node v4.8.2

### ISSUE THREAD

**Issue by bastien-roucaries** [crypto-browserify/browserify-aes#44]
Test suite fail see txt file joinded. Using master and lasted version
[fail.txt](https://github.com/crypto-browserify/browserify-aes/files/1033563/fail.txt)

**Comment by dcousens** [comment]
Will take this,  its related to https://github.com/crypto-browserify/browserify-aes/pull/41 - I thought Travis had passed all green...

**Comment by bastien-roucaries** [comment]
Any news ?

**Comment by dcousens** [comment]
On my priorities,  just hit a few other bumps before I could get to it.

**Comment by bastien-roucaries** [comment]
It seems that the error is due to change in recent buffer-xor

**Comment by pravi** [comment]
from #debian-js irc,

> Shanavas: does it take a lot of effort to make it work with buffer-xor 2?
> The issue is fairly simple, 00ff0f xor f0f0 gives f00f in v1 and f00f0f in v2
> 
> Don't know how this affects aes algorithm

@dcousens what do you think?
