### ISSUE TITLE
Can we  drop evp_bytestokey for better alternatives?

### ISSUE THREAD

**Issue by pravi** [crypto-browserify/browserify-aes#47]
This was raised in debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868298 since EVP_BytesToKey description says ""is not actually secure, only every use it for compatibility reasons"

**Comment by calvinmetcalf** [comment]
this module is just a port of node.js's crypto library into the browser and  EVP_BytesToKey in all it's non secure glory is what they use for deriving a key and and an IV from a plaintext password.

**Comment by dcousens** [comment]
> is not actually secure, **only every use it for compatibility reasons**

Which is why we have it :+1:
