### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by diasdavid** [crypto-browserify/browserify-aes#49]
Following https://github.com/crypto-browserify/browserify-aes/pull/48 and amazing results such as https://github.com/libp2p/js-libp2p-secio/issues/92#issuecomment-326838744, we really need this update. 

Could you release as soon as possible? Thank you!

**Comment by dcousens** [comment]
Closing in favour of https://github.com/crypto-browserify/browserify-aes/pull/50
