### ISSUE TITLE
browserify-aes dependency broken with npm install

### ISSUE THREAD

**Issue by Rob-Leggett** [crypto-browserify/browserify-aes#51]
Browserfiy-aes is trying to pull down a dependency that does not exist evp_bytestokey@^1.0.3 and when running npm install it is failing.

npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: evp_bytestokey@^1.0.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.2, 1.0.1, 1.0.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'browserify-aes'
npm ERR! notarget

**Comment by dcousens** [comment]
Closing in favour of https://github.com/crypto-browserify/browserify-aes/issues/51
