### ISSUE TITLE
AES-GCM-256 with 16 zero byte IV. 

### ISSUE THREAD

**Issue by sublimator** [crypto-browserify/browserify-aes#53]
An Apple Wallet product (as much as I can say due to NDA) uses aes-gcm-256. The 32 byte key is created using a kdf with ECDH derived key material. As the keys are only ever used once, Apple is using a 16 byte IV with all zero bytes. 

We developed an implementation of the Apple crypto protocol that works using the `crypto` module, but seems to fail with browserify-aes, hitting an assertion of IV length == 12. When commenting out that assertion, it complains about a bad authentication state/tag (or the like)

I'm not really up to speed with AES/GCM so not sure where to start with this, but I could help out with some failing tests if that would be of assistance.

**Comment by sublimator** [comment]
cc @scottire

**Comment by dcousens** [comment]
Any test data/vectors?

**Comment by sublimator** [comment]
Should I open a pull request with patches to the test suite ?

**Comment by calvinmetcalf** [comment]
so at least when I wrote this you'd get an error if you used an IV in node that was longer then 12 bytes but that seems no longer to be the case, since 16 and 12 length buffers that are all zeros are not treated the same this may be slightly more complex then just removing the check because I seam to remember thing in the GCM spec about using the Galois number field thing to deal with bigger IV lengths

**Comment by sublimator** [comment]
It's all double dutch, Galois too much, to me ... 

I did try just removing the check though yeah :)

**Comment by calvinmetcalf** [comment]
the check probably makes the code work, but likely you'll get different responses compared to the node version, if thats ok then just truncate the IV to 12 on the browser version (or if it's not truncate it for both), in the mean time I can see about implementing the longer IV handling though you're correct it's pretty complex so it may be a bit of time

**Comment by sublimator** [comment]
> you're correct it's pretty complex so it may be a bit of time

Honestly no idea :)

Would you like me to add some cases to the test suite ?

**Comment by sublimator** [comment]
I can get onto that tomorrow if so

**Comment by calvinmetcalf** [comment]
I've created some tests locally and have started looking into it, but have gotten side track when some real stuff from my day job came up I'll be able to circle back at some point but if you're in a hurry, try using 12 byte IVs it'll probably be faster too

**Comment by sublimator** [comment]
The 16 byte IVs are kind of dictated by Apple unfortunately.

**Comment by sublimator** [comment]
Thanks for looking into it :)

**Comment by sublimator** [comment]
Awesome, thanks guys :)
